(DEFUN ADD-LENGTHS (LIST1 LIST2)
  (+ (LENGTH LIST1) (LENGTH LIST2)))

(DEFUN ADD-LENGTH-TO-LIST (LIST)
    (APPEND LIST (LIST (LENGTH LIST))))

(DEFUN PALINDROME-P (LIST)
    (EQUAL LIST (REVERSE LIST)))

(DEFUN WHAT-IS-IT (ARG)
    (COND ((NUMBERP ARG) 'NUMBER)
    ((SYMBOLP ARG) 'S-ATOM)
    ((LISTP ARG) 'LIST)
    (T 'DO-NOT-KNOW)))